"""add cloud resource optimization models

Revision ID: 8657b99b942c
Revises: 5dd53ce1aed9
Create Date: 2026-09-26 09:36:09.771985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8657b99b942c'
down_revision = '5dd53ce1aed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.String(length=150), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('cpu_capacity', sa.Float(), nullable=False),
    sa.Column('memory_capacity', sa.Float(), nullable=False),
    sa.Column('storage_capacity', sa.Float(), nullable=False),
    sa.Column('network_capacity', sa.Float(), nullable=False),
    sa.Column('current_cpu_usage', sa.Float(), nullable=False),
    sa.Column('current_memory_usage', sa.Float(), nullable=False),
    sa.Column('current_storage_usage', sa.Float(), nullable=False),
    sa.Column('current_network_usage', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('current_utilization', sa.Float(), nullable=False),
    sa.Column('recommended_utilization', sa.Float(), nullable=True),
    sa.Column('estimated_monthly_savings', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['cloud_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optimization_recommendations')
    op.drop_table('cloud_resources')
    # ### end Alembic commands ###
